nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']  # Dodaj adresy URL, z których chcesz zezwolić na dostęp
            allow_headers: ['X-Requested-With', 'Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS']  # Określ dozwolone metody HTTP
            max_age: 3600  # Opcjonalnie: maksymalny czas przechowywania w sekundach dla preflight requests
        '^/': null
